name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        # Добавили default-jdk, чтобы компилятор javac был доступен глобально
        sudo apt install -y git zip unzip openjdk-17-jdk default-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libffi-dev libssl-dev aapt
        
        pip install --upgrade pip
        pip install "setuptools<70" "cython<3" 
        pip install git+https://github.com/kivy/buildozer.git
        pip install git+https://github.com/kivy/python-for-android.git

    - name: Build APK with Buildozer
      run: |
        # Гарантируем, что JAVA_HOME указывает куда нужно перед запуском сборки
        export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
        export PATH=$PATH:$JAVA_HOME/bin

        # Полная очистка и сборка
        rm -rf "$HOME/.buildozer"
        buildozer android clean
        buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: LatenessTracker_APK
        path: bin/*.apk
